#!/bin/sh

NFT=$(which nft)
SYSTEMCTL=$(which systemctl)

RAND=false
MAC=false
STOP=false
RELOAD=false

DIR=/lib/paranoid-ninja
if [ -f $DIR/functions ] ; then
  FUNCS="$DIR/functions"
fi

source $FUNCS
loadEnv

######################################################
# Stop

stopParanoid() {
  if [[ $firewall == "nftables" ]] ; then
    $NFT flush ruleset
  elif [[ $firewall == "iptables" ]] ; then
    clearIptables
  else
    echo "$firewall is no valid"
    exit 1
  fi
}

######################################################
# Command options

while [ "$#" -gt 0 ] ; do
  case "$1" in
    -r | --randomize)
      RAND=true
      shift
      ;;
    -m | --mac)
      MAC=true
      shift
      ;;
    -R | --reload)
      RELOAD=true
      shift
      ;;
    -c | --config)
      CONF="$2"
      checkConfigFile "$2"
      shift
      shift
      ;;
    -s | --stop)
      STOP=true
      shift
      ;;
    *)
      die "%s\\n" "Invalid option '$1'"
      ;;
  esac
done

if [[ $MAC == true ]] ; then
  . $LIB_DIR/randomize.sh -c $CONF
fi

if [[ $RAND == true ]] && [[ $CONF ]] ; then
  . $LIB_DIR/randomize.sh -c $CONF
fi

if [[ $RELOAD == true ]] && [[ $CONF ]] ; then
  . $LIB_DIR/randomize.sh -c $CONF
  loadTor
fi

if [[ $STOP == true ]] && [[ $CONF ]] ; then
  stopParanoid
fi
