#!/bin/sh

NFT=$(which nft)
SYSTEMD_S="/usr/lib/systemd/scripts"
readonly prog_name="$0"

######################################################
# Randomize

randomize() {
  . $SYSTEMD_S/randomize.sh -c $CONF
}

######################################################
# Stop

stopParanoid() {
  $NFT flush ruleset
  # TODO: reinstall all files in backup dir
}

######################################################
# Command options

if [ "$#" -eq 0 ]; then
    printf "%s\\n" "$prog_name: Argument required"
    exit 1
fi

while [ "$#" -gt 0 ] ; do
  case "$1" in
    -r | --randomize)
      RAND=true
      shift
      ;;
    -c | --config)
      CONF="$2"
      shift
      shift
      ;;
    -s | --stop)
      stopParanoid
      shift
      ;;
    *)
      printf "%s\\n" "$prog_name: Invalid option '$1'"
      exit 1
      ;;
  esac
done

if [[ $RAND ]] && [[ $CONF ]] ; then
  randomize
fi
